exp_id: exp-2
seed: 123

data:
  dataset_name: celltreeqm_dataset/lg_bd_ntips100_len5000
  lineage_name: celltreeqm-lg-bd
  dataset_names:
    train: 0.5
    test: 0.5
  autosplit: sites

training:
  batch_size: 4096
  lr: 0.0003
  num_epochs: 20
  eval_interval: 300
  warmup_steps: 500
  grad_clip: 1.0
  p_warmup_steps: 500

loss:
  weight_gate: -1.0
  weight_decay: 0.0001
  weight_D: 1
  weight_P: 10.0
  weight_close: 1.0
  weight_push: 5.0
  push_margin: 0.1
  distance_error_alpha: 0.75
  D_align: scale  
  adaptive_P: true
  adaptive_P_ema: 0.9
  adaptive_P_target_ratio: 0.5
  p_warmup_steps: 500
  
model:
  metric: euclidean
  metric_loss: additivity
  cell_encoder_type: site_setpool # linear, site_token, site_setpool
  # CellTreeQM ----------------------
  proj_dim: 512
  output_dim: 128
  hidden_dim: 512
  num_heads: 4
  num_layers: 4
  dropout_data: 0
  dropout_metric: 0.1
  norm_method: none # batch_norm, layer_norm, none
  gate_type: none  
  # CellEncoder ----------------------
  site_alphabet_size: 22
  site_embed_dim: 32
  site_encoder_heads: 4
  site_encoder_layers: 1
  site_dropout: 0.1
  site_pma_seeds: 8
  site_chunk_size: 1