name: py_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - numpy
  - pandas
  - jupyter
  - ipykernel
  - leidenalg
  - python-igraph
  - nose
  - scanpy
  - scipy
  - louvain
  - hyperopt
  - loompy
  - cmake
  - dill
  - ipython
  - bbknn
  - seaborn
  - matplotlib
  - request
  - cython
  - snakemake
  - pyqt
  - anytree
  - biopython
  - ete3
  - dendropy   
  - r-base
  - r-essentials
  - r-igraph
  - rpy2
  - fastme
  - pip:
      - scvi-tools
      - torch
      - torchvision
      - torchaudio
      - tensorboard
      - torch-tb-profiler
      - ruamel.yaml
      - wandb
      - cvxpy
      - synapseclient
      - python-dotenv
      - tqdist
      - ray[data,train,tune,serve]
